<a href="https://colab.research.google.com/github/Akbar-AI97/ai_foundation/blob/main/numpy_MIT36.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# pip install numpy


In [10]:
# 1D array

import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

numpy_array: [1 3 5 7]


In [17]:
# 2D array -> matrix

import numpy as np

arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array2:', arr2)

arr2.shape

numpy_array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [21]:
# dtype
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [28]:
# reshape()

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [30]:
#  astype()

a = np.array([1, 2, 3])
b = a.astype(float)

print("float:", b)

float: [1. 2. 3.]


In [33]:
# np.zeros(), np.ones() => dummy data

z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# ndim => used to find dimension

a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [39]:
# arange() => used to create array for test data

a = np.arange(1, 6)

print("arange:", a)

arange: [1 2 3 4 5]


In [41]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum: ", a.sum())
print("mean: ", a.mean())
print("max: ", a.max())
print("min: ", a.min())

sum:  10
mean:  2.5
max:  4
min:  1


In [43]:
# flatten() => 2D/3D -> into 1D array

a = np.array([[1, 2], [3, 4]])
b = a.flatten()

print("flatten:", b)

flatten: [1 2 3 4]


In [46]:
# T (Transpose)

a = np.array([[1, 2], [3, 4]])
print("transpose: ", a.T)

transpose:  [[1 3]
 [2 4]]


In [51]:
# dot() - @ (Matrix maltiplication)

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

# print("dot/maltiplication: ", a.dot(b))
print("dot/maltiplication: ", a @ b)

dot/maltiplication:  [[ 4  4]
 [10  8]]


In [54]:
# random.rand() - creates random numbers between [0, 1)

a = np.random.rand(2, 3)
print("random: ", a)

random:  [[0.95657875 0.2754953  0.57938819]
 [0.72229675 0.78690911 0.74140829]]
