<a href="https://colab.research.google.com/github/Akbar-AI97/ai_foundation/blob/main/students_performance_MIT36.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install pandas numpy

In [10]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("StudentsPerformance.csv")

print("Dataset shape (rows, columns): ", df.shape)
print("Column names: ", df.columns.tolist())
print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns):  (1000, 8)
Column names:  ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  

In [24]:
print("Average score by columns:")
df[["math score", "reading score", "writing score"]].mean()

Average score by columns:


,0
math score,66.089
reading score,69.169
writing score,68.054


In [26]:
print("Max score by subjects:")
df[["math score", "reading score", "writing score"]].max()

Max score by subjects:


,0
math score,100
reading score,100
writing score,100


In [28]:
print("Min score by subjects:")
df[["math score", "reading score", "writing score"]].min()

Min score by subjects:


,0
math score,0
reading score,17
writing score,10


---------- Correlation ------------

Correlation is a statistical measure that shows how strongly two variables in a dataset are related. In AI and machine learning, it helps identify whether changes in one feature are associated with changes in another.

Positive correlation (+1): As one variable increases, the other also increases.
Example: More study hours → Higher exam scores.

Negative correlation (-1): As one variable increases, the other decreases.
Example: Higher product price → Lower sales.

No correlation (0): The variables have no meaningful relationship.
Example: Shoe size and exam score.

In [33]:
# Correlation

print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()

Correlation:


,math score,reading score,writing score
math score,1.000000,0.817580,0.802642
reading score,0.817580,1.000000,0.954598
writing score,0.802642,0.954598,1.000000


In [36]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 60, "Yes", "No") # condition(true) ? "Yes" : "No"

print("New columns preview (total, average, passed): ")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed): 
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes


In [50]:
# test preparation course - based average
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("Average Student score by test preparation:")
print(test_prep_group)

print("\n")

# gender - based average
gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("Average Student score by gender:")
print(gender_avg)

print("\n")

# Students "passed" vs "failed"
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Students passed vs failed:")
print(pass_rate)

Average Student score by test preparation:
                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673


Average Student score by gender:
        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203


Students passed vs failed:
passed
Yes    71.5
No     28.5
Name: proportion, dtype: float64


In [63]:
# Convert scores to Numpy array

scores = df[["math score", "reading score", "writing score"]].values

# mean, std deviation
print("Mean:", np.mean(scores, axis=0))
print("Std deviation:", np.std(scores, axis=0))
print("\n")

# Z-scores (normalize)
z_scores = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores:\n", z_scores[:5])

# Average is 0  | Negative -  | Positive +

Mean: [66.089 69.169 68.054]
Std deviation: [15.15549666 14.59289002 15.18805728]


Z-scores:
 [[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]


In [66]:
# How many students scored above 90 on average?
top_scores = df[df["average score"] >= 90]
print("Top Students who scored above 90:", len(top_scores))

# How many failed?
failed_students = df[df["passed"] == "No"]
print("Failed Students:", len(failed_students))

Top Students who scored above 90: 52
Failed Students: 285
